/* Formatted on 10/8/2022 4:04:59 PM (QP5 v5.287) */
DECLARE
   TYPE USER_TYPE IS TABLE OF FND_USER%ROWTYPE
      INDEX BY PLS_INTEGER;

   L_USER_LIST   USER_TYPE;
   i             NUMBER;
BEGIN
   FOR USER_REC IN (  SELECT *
                        FROM FND_USER FU
                       WHERE 1 = 1 AND ROWNUM < 6 AND USER_ID IS NOT NULL
                    ORDER BY USER_ID)
   LOOP
      L_USER_LIST (USER_REC.USER_ID) := USER_REC;
   END LOOP;

   I := L_USER_LIST.FIRST;
   DBMS_OUTPUT.PUT_LINE (L_USER_LIST (I).USER_NAME);
   I := L_USER_LIST.LAST;
   DBMS_OUTPUT.PUT_LINE (L_USER_LIST (I).USER_NAME);
END;