SET DEFINE OFF;
Prompt drop TABLE XXDL_FND_USERS;
DROP TABLE XXDL_FND_USERS CASCADE CONSTRAINTS PURGE
/

Prompt Table XXDL_FND_USERS;
--
-- XXDL_FND_USERS  (Table) 
--
--  Dependencies: 
--   XXDL_FND_RESPONSIBILITY_TYPE (Type)
--   STANDARD (Package)
--
CREATE TABLE XXDL_FND_USERS
(
  USER_ID                NUMBER,
  USER_NAME              VARCHAR2(100 BYTE),
  EMAIL                  VARCHAR2(100 BYTE),
  RESPONSIBILITIES_LIST  XXDL_FND_RESPONSIBILITY_TYPE
)
NESTED TABLE RESPONSIBILITIES_LIST STORE AS USER_RESPONSIBILITIES
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/


--  There is no statement for index SYS.SYS_C007540.
--  The object is created when the parent object is created.
