SET DEFINE OFF;
Prompt drop Type XXDL_FND_RESPONSIBILITY_OBJ;
DROP TYPE XXDL_FND_RESPONSIBILITY_OBJ
/

Prompt Type XXDL_FND_RESPONSIBILITY_OBJ;
--
-- XXDL_FND_RESPONSIBILITY_OBJ  (Type) 
--
--  Dependencies: 
--   STANDARD (Package)
--
/* Formatted on 11/11/2022 4:18:07 PM (QP5 v5.287) */
CREATE OR REPLACE TYPE XXDL_FND_RESPONSIBILITY_OBJ AS OBJECT
(
   APPLICATION_ID NUMBER,
   RESPONSIBILITY_ID NUMBER
);
/
SHOW ERRORS;
