SET DEFINE OFF;
Insert into SYS.XXDL_FND_USERS
   (USER_ID, USER_NAME, EMAIL, RESPONSIBILITIES_LIST)
 Values
   (1, 'demasy', 'demasy@demasy.io', SYS.XXDL_FND_RESPONSIBILITY_TYPE(
      "SYS".XXDL_FND_RESPONSIBILITY_OBJ(1,1)));
Insert into SYS.XXDL_FND_USERS
   (USER_ID, USER_NAME, RESPONSIBILITIES_LIST)
 Values
   (2, 'ahmed', SYS.XXDL_FND_RESPONSIBILITY_TYPE(
      "SYS".XXDL_FND_RESPONSIBILITY_OBJ(2,2)));
COMMIT;
